// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'us-east-1:f8d2c9d3-22f9-4de7-a8b2-88eb298dfd0a';
var aws_cognito_region = 'us-east-1';
var aws_content_delivery = 'enable';
var aws_content_delivery_bucket = 'votefromabroad-hosting-mobilehub-687916863';
var aws_content_delivery_bucket_region = 'us-east-1';
var aws_content_delivery_cloudfront = 'enable';
var aws_content_delivery_cloudfront_domain = 'd31eu57a9bj427.cloudfront.net';
var aws_mobile_analytics_app_id = 'be9cb4e6d9c0438dba740c2dfa1717ac';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = '678b1f63-38ef-4885-9b7a-25e03e913621';
var aws_project_name = 'VoteFromAbroad';
var aws_project_region = 'us-east-1';
var aws_resource_name_prefix = 'votefromabroad-mobilehub-687916863';
var aws_sign_in_enabled = 'enable';
var aws_user_pools = 'enable';
var aws_user_pools_id = 'us-east-1_aXuRvIHe4';
var aws_user_pools_mfa_type = 'ON';
var aws_user_pools_web_client_id = '5ehiffe6s5stq8hpf401k7096a';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
