categories:
  - Addressing / Mailing Instructions
  - Ballot Related Issues
  - Dates and Deadlines
  - Eligibility / First Time Voter
  - FWAB - Emergency Write-in Ballot
  - Form Related Issues
  - Glossary - Terms
  - Other Related Issues
  - Party Affiliation Questions
  - Primary Elections
  - Registration Process
  - Security and Privacy
  - Technical Issues
  - US Citizens without Residency
  - Voter Account Issues
  - Voter ID
